### ISSUE TITLE
facedetection_images.py has no option output_string

### ISSUE THREAD

**Issue by Bartcardi** [natanielruiz/dockerface#1]
Hi Nataniel,

In your instructions in the README.md file I found two small errors:
1. > Use this command to **process an image** 

refers to `tools/run_face_detection_on_video.py`

2. > Also if you are looking to conveniently **process all images in one folder** use this command

uses the flag `--output_string` which is not there. `--output_folder` is there though.

Great work by the way!

**Comment by natanielruiz** [comment]
You're right! Thank you very much. It is now fixed.
