### ISSUE TITLE
CPU only verison ? 

### ISSUE THREAD

**Issue by MyraBaba** [natanielruiz/dockerface#3]
Is CPU version availabe ? And can use it for live camera feed ?

Thx

**Comment by natanielruiz** [comment]
This project is mostly directed for processing large quantities of data and that is why it's GPU only - sorry! I hope you find what you need.

If there is enough demand I could make a CPU only version but it would be pretty slow (wouldn't work on a live camera feed, would take about 2-3 seconds per image).

Cheers
