### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_70'

### ISSUE THREAD

**Issue by learnbott** [natanielruiz/dockerface#4]
I get this error when running the `make -j20` line while trying to compile Caffe. I am using an AWS GPU server with the new NVIDIA Voltas. Any hint how to fix this error?

**Comment by natanielruiz** [comment]
This might have something to do with the NVIDIA GPU you're using. Maybe this issue might help you: https://github.com/ethereum-mining/ethminer/issues/454

Please post an update on here if modifying the makefile works.

**Comment by natanielruiz** [comment]
@learnbott Any luck?

**Comment by natanielruiz** [comment]
Closing this for lack of follow up.
